# Generated by Django 4.2 on 2023-04-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
    ]
