# Generated by Django 4.2 on 2023-05-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_category_image_url_brand_alter_car_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url_brand',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
